config/routes.rb
Rails.application.routes.draw do
  root to: 'profile#dashboard'
  devise_for :users,:controllers => {:registrations => "registrations"}
  resources :transactions
  resources :accounts
  resources :users

  namespace :api do
    resources :users, only: [:index, :show, :create, :update]
  end

  get '/profile/info' => 'profile#info'

  get '/profile/:account_id/deposit' => 'profile#deposit', as: :deposit
  post '/profile/:account_id/do_deposit' => 'profile#do_deposit', as: :do_deposit

  get '/profile/:account_id/withdraw' => 'profile#withdraw', as: :withdraw
  post '/profile/:account_id/do_withdraw' => 'profile#do_withdraw', as: :do_withdraw


end

app/controllers/transactions_controller.rb
class TransactionsController < AdminController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @account = Account.find_by(id: @transaction.account_id)
    @user = User.find_by(id: @account.user_id)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:account_id, :amount, :currency, :transaction_type)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.text_field :account_id, id: :transaction_account_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :transaction_amount %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency, id: :transaction_currency %>
  </div>

  <div class="field">
    <%= form.label :transaction_type %>
    <%= form.text_field :transaction_type, id: :transaction_transaction_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path , :class => "button1" %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Transaction type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.account.id %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.currency %></td>
        <td><%= transaction.transaction_type %></td>
        <td><%= link_to 'Show', transaction, :class => "button1" %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction), :class => "button1" %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'button1' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path, :class => "button1" %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path , :class => "button1" %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Account:</strong>
  <%= @transaction.account.id %>
</p>

<p>
  <p>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @transaction.currency %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @transaction.transaction_type %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction), :class => "button1" %>
<%= link_to 'Back', transactions_path,:class => "button1" %>