config/routes.rb
Rails.application.routes.draw do
  root to: 'profile#dashboard'
  devise_for :users,:controllers => {:registrations => "registrations"}
  resources :transactions
  resources :accounts
  resources :users

  namespace :api do
    resources :users, only: [:index, :show, :create, :update]
  end

  get '/profile/info' => 'profile#info'

  get '/profile/:account_id/deposit' => 'profile#deposit', as: :deposit
  post '/profile/:account_id/do_deposit' => 'profile#do_deposit', as: :do_deposit

  get '/profile/:account_id/withdraw' => 'profile#withdraw', as: :withdraw
  post '/profile/:account_id/do_withdraw' => 'profile#do_withdraw', as: :do_withdraw


end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions
  belongs_to :user
end

app/controllers/accounts_controller.rb
class AccountsController < AdminController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to root_path, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :amount, :currency)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :account_user_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :account_amount %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency, id: :account_currency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path , :class => "button1" %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Amount</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.user.name %></td>
        <td><%= account.amount %></td>
        <td><%= account.currency %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'button1' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path , :class => "button1" %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path , :class => "button1" %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @account.user.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @account.amount %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @account.currency %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path , :class => "button1" %>